name: sbe
description: A new Flutter project.

publish_to: 'none'

version: 2.0.4+16

environment:
  sdk: '>=2.18.6'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_database: ^11.3.4
  firebase_storage: ^12.4.4
  google_fonts: ^6.2.1
  carousel_slider: ^5.0.0
  photo_view: ^0.15.0
  image_picker: ^1.1.2
  url_launcher: ^6.1.7
  google_maps_flutter: ^2.2.2
  file_picker: ^9.2.3
  flutter_cached_pdfview: ^0.4.1
  new_version_plus: ^0.1.0
  share_plus: ^10.1.4
  shared_preferences: ^2.0.20
  pdf: ^3.8.4
  label_marker: ^1.0.1
  permission_handler: ^11.4.0
  change_app_package_name: ^1.1.0
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.3
  flutter_lints: ^5.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/balaji_cat_icon.png"

flutter:
  uses-material-design: true
